version: '3.8'

services:
  db:
    image: postgres:14
    container_name: psicoagenda-db
    restart: always
    environment:
      POSTGRES_DB: psicoagenda_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data